### ISSUE TITLE
Link Module Won't Accept Blacklight "or" facets

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/pul_library_drupal#1317]
Module's link validation code seems to be stripping repeated param values. Some branches (Art, Music) wish to link to scoped subsets of location codes. 

Example:

https://pulsearch.princeton.edu/catalog?utf8=%E2%9C%93&f1=all_fields&q1=&op2=AND&f2=author&q2=&op3=AND&f3=title&q3=&f_inclusive%5Badvanced_location_s%5D%5B%5D=rcppz&f_inclusive%5Badvanced_location_s%5D%5B%5D=sax&range%5Bpub_date_start_sort%5D%5Bbegin%5D=&range%5Bpub_date_start_sort%5D%5Bend%5D=&sort=score+desc%2C+pub_date_start_sort+desc%2C+title_sort+asc&search_field=advanced&commit=Search

**Comment by axamei** [comment]
Changed URL to be a bitly and it works.
