### ISSUE TITLE
library-prod4 not shipping to datadog

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/pul_library_drupal#1556]
while looking through the datadog logs I notice library-prod4 is not shipping logs to datadog.

**Comment by carolyncole** [comment]
Double checked and it is there now...
![Screen Shot 2020-11-17 at 10 24 34 AM](https://user-images.githubusercontent.com/1599081/99409198-1c15fe00-28bf-11eb-9066-0a34bc990858.png)
