### ISSUE TITLE
Add capistrano task to sync production files to staging

### ISSUE THREAD

**Issue by axamei** [pulibrary/pul_library_drupal#1591]
We want to be able to copy files in `/mnt/diglibdata/drupalweb/production_files` to `/mnt/diglibdata/drupalweb/staging_files` on library-staging

**Comment by carolyncole** [comment]
Here is the command `sudo -u www-data cp -r /mnt/diglibdata/drupalweb/production_files/* /mnt/diglibdata/drupalweb/staging_files/`
