### ISSUE TITLE
Review Editor HTML Allowed Tags

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/pul_library_drupal#1612]
Review the CK editor feature profile assigned to this wswyig mode. I think headers aren't part of the buttons users with this privilege level aren't seeing this.

**Comment by axamei** [comment]
Signed in as a user with new editing privileges and I see the heading options:
<img width="1068" alt="Screen Shot 2020-03-31 at 10 49 14 AM" src="https://user-images.githubusercontent.com/8161144/78040406-62711980-733d-11ea-9d85-82f548748cf1.png">

We can look into moving it / rearranging the wysiwyg options to make it a little more visible.

**Comment by kevinreiss** [comment]
Maybe one to revisit when we get to Drupal 9.
