### ISSUE TITLE
Assets missing from some admin pages in prod only

### ISSUE THREAD

**Issue by axamei** [pulibrary/pul_library_drupal#1618]
possibly related to the js issues when logged in refs #1589 

<img width="1680" alt="Screen Shot 2020-04-30 at 10 13 33 AM" src="https://user-images.githubusercontent.com/8161144/80720700-480c9600-8acb-11ea-8cd4-9f394598611b.png">

**Comment by axamei** [comment]
This is not an issues on staging

**Comment by axamei** [comment]
<img width="840" alt="Screen Shot 2020-05-06 at 3 20 33 PM" src="https://user-images.githubusercontent.com/8161144/81294274-a4783400-903c-11ea-9ee1-8ed919685c87.png">

These errors are coming from attempting to edit a user node.

**Comment by carolyncole** [comment]
Tomorrow morning...
```
ssh pulsys@library-prod1
sudo mv production_files/css production_files/css_sav
sudo mv production_files/js production_files/js_sav
sudo mkdir production_files/css
sudo mkdir production_files/js
sudo chown www-data:deploy production_files/js
sudo chown www-data:deploy production_files/css
sudo su - deploy
cd /var/www/library_cap/current
drush vdel drupal_js_cache_files && drush vdel drupal_css_cache_files
drush cc all
```

**Comment by kevinreiss** [comment]
👍
