### ISSUE TITLE
Upgrade phpCAS

### ISSUE THREAD

**Issue by axamei** [pulibrary/pul_library_drupal#1620]
We are on 1.3.3, but current version is 1.3.8. 1.3.5 had security vulnerabilities.

Latest version: https://apereo.atlassian.net/wiki/spaces/CASC/pages/103252517/phpCAS

https://github.com/pulibrary/pul_library_drupal/tree/46f94c8f1201a25657da8b95b47a660910e9a130/sites/all/libraries/CAS

**Comment by axamei** [comment]
Check https://github.com/pulibrary/pul_library_drupal/tree/phpcas on staging

**Comment by kevinreiss** [comment]
Deployed to prod.
