### ISSUE TITLE
Ck Editor Console Error

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/pul_library_drupal#1640]
This was general on the edit view of the architecture homepage when selected the link dialog in the editor. 

<img width="1776" alt="Screen Shot 2020-07-22 at 11 00 48 AM" src="https://user-images.githubusercontent.com/278825/88199966-16f3bb80-cc0b-11ea-87f5-e1d1853a6dc8.png">

**Comment by axamei** [comment]
Cannot reproduce. This might have been resolved by the updating the version of jquery.
