### ISSUE TITLE
Quoted searches fail in the all search

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/pul_library_drupal#1641]
Reported by Jeremy Darrington, confirmed this is an issue. Suspect it may be an encoding issue with either a recent release of the panels module or an issue within discoveryutils. Example:

Searches using quotation marks no longer return results no longer return results from Articles+ (nor, it appears, from the Catalog). See https://library.princeton.edu/find/all/%22Political%20order%20and%20political%20decay%22 vs. https://library.princeton.edu/find/all/Political%20order%20and%20political%20decay

I suspect it's likely discoveryutils since a simpler search with content in the local drupal solr index does bring back viable results. 

https://library.princeton.edu/find/all/%22Kevin%20Reiss%22

**Comment by axamei** [comment]
closing in favor of https://github.com/pulibrary/discoveryutils/issues/158
