### ISSUE TITLE
Add Bento Box Result Block for Pulfalight

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/pul_library_drupal#1662]
Update the Finding Aids block to pull data from Pulfalight. Time release with launch of pulfalight.

**Comment by axamei** [comment]
@kevinreiss  @sdellis This bento is currently not working. Getting no results: https://library.princeton.edu/utils/pulfa/any?query=fitzgerald&sid=library-main. We should revisit this now that pulfalight is publicly available.
