### ISSUE TITLE
Create Protected Form to Record Staff Information for Alert Text Bank

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/pul_library_drupal#1663]
Create a form protected by SSO to record the phone numbers staff agree to accept emergency texts from the Library at. Use the webform module and record the following data points.

[Boilerplate text about what you are agreeing to, communications to provide]

1. Staff Name
2. Wireless Carrier
3. Phone number.

**Comment by axamei** [comment]
@kevinreiss Who should the form send the values to? Emily and Barbara?

**Comment by kevinreiss** [comment]
Let me ask them if they want to get a notification for every submission. I was thinking they'd go download the responses as a spreadsheet when they wanted to collect them.

**Comment by kevinreiss** [comment]
@axamei no need to send a confirmation email to anyone when there is a submission.

**Comment by kevinreiss** [comment]
Two pieces of feedback from coms:

1. Can the wireless carriers be a dropdown?
2. Change “Carrier fees apply...” to be “Carrier fees apply.”

**Comment by axamei** [comment]
@kevinreiss Dropdown would make sense if they are sending these texts via email and we were associating the carrier domains, e.g., @vtext.com for verizon. If we want the wireless carriers to be a dropdown, then they need to supply those values. We can't be certain that all staff use the major wireless carriers. IMO we can be more inclusive with the field as free text.
