### ISSUE TITLE
Retire Hours Features

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/pul_library_drupal#1664]
- [x] Redirect old individual hours pages 
- [x] Remove data associated with Hours
- [x] Remove content types/features associated with hours.

**Comment by axamei** [comment]
@kevinreiss do we need to add a means for OIT to grab library hours? refs #1416

**Comment by axamei** [comment]
We also need to replace the hours for discoveryutils /utils/hours used by special collections.

**Comment by axamei** [comment]
- [ ] Delete all Library Hours nodes
- [ ] Remove Library Hours from Shortcuts
- [ ] Disable library_hours feature/module
- [ ] Uninstall library_hours module
- [ ] Remove Library Hours content type
- [ ] Remove Hours Editor role to users
- [ ] Remove Hours Editor role
