### ISSUE TITLE
Users who do not match the HR ID

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/pul_library_drupal#1668]
We should update the user id on these folks to match with the HR report, or they will
 end up in the system twice

![Screen Shot 2020-11-16 at 4 02 31 PM](https://user-images.githubusercontent.com/1599081/99307904-27b4e680-2825-11eb-8831-d3b52e65ea98.png)
```
kayiwa => fkayiwa
dmacdonald => dam9 
```

People who do NOT exist in the Finance Report, but do exist in HR:
```
aberdini
boatman
```

**Comment by kevinreiss** [comment]
We can update the first two and ask to check his database to make sure the latter two are properly attached to positions.

**Comment by carolyncole** [comment]
Based on error messages from parsing... https://library.princeton.edu/import/pul_library_staff_importer/log
Complete list of names not in the finance database:
```
rg9732
eg3321
jb0737
cj0577
brj2
cvansant
kavitak
psayer
boatman
```

Person with bad email address:  gissood has a pren in their email
