### ISSUE TITLE
Retire "Training" Features

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/pul_library_drupal#1674]
- [x] Get sign off from Audrey W. that we are done with this in favor of LibCal reservations. 
- [x] Remove views/panels attached to this feature. 
- [x] Remove training series and training content types. 
- [x] Remove entity forms.
- [ ] Remove entity forms module (I believe this was our only instance where that was used)

**Comment by axamei** [comment]
There are other entity forms. I suspect that after a review of these entity forms, we can remove them and the module.

**Comment by kevinreiss** [comment]
Yes, there isn't anything I remember other than training forms that actually used entity forms in production.
