### ISSUE TITLE
SSO Protect Recommend a Purchase Form

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/pul_library_drupal#1680]
Only all PU directory account holders to access this form.

**Comment by axamei** [comment]
Form is now for authenticated users only

**Comment by kevinreiss** [comment]
@axamei  Looks like it is still open under captcha? (was going to close an old SN@P ticket and checked)

**Comment by axamei** [comment]
@kevinreiss try it in new/private browser. i get the following:
<img width="1904" alt="Screen Shot 2020-12-10 at 9 55 16 AM" src="https://user-images.githubusercontent.com/8161144/101788232-dddeb980-3acd-11eb-8410-4b3e78024ea3.png">
