### ISSUE TITLE
Create Landing Page for Office of Research Data and Open Scholarship

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/pul_library_drupal#1699]
Mockup - https://drive.google.com/drive/folders/136Hh4vtig_1FIEd1yd3Hzwg_TSK-ta0b (in eus drive)
Banner Graphic - https://drive.google.com/file/d/1CN2P0AH_3NDPHILRvd_8MvprgrtcoZZx/view?usp=sharing_eip&ts=603d0162

URL: https://library.princeton.edu/rdos or https://library.princeton.edu/research-data-open-scholarship

**Comment by axamei** [comment]
@kevinreiss both urls are currently redirecting to researchdata.princeton.edu we need to remove this redirect if they want these urls for this page

**Comment by axamei** [comment]
This is on https://library-staging.princeton.edu/rdos
