### ISSUE TITLE
Link to Content Button Produces Ajax Error in Editor

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/pul_library_drupal#1717]
<img width="157" alt="Screen Shot 2021-04-12 at 3 39 18 PM" src="https://user-images.githubusercontent.com/278825/114458791-49808280-9ba5-11eb-9d96-07ab82bef1f9.png">

First linking option.

**Comment by kevinreiss** [comment]
<img width="468" alt="Screen Shot 2021-04-12 at 3 40 17 PM" src="https://user-images.githubusercontent.com/278825/114458875-67e67e00-9ba5-11eb-946d-486d8a816be7.png">

**Comment by axamei** [comment]
Added support for Editor text format in LinkIt profile. Fixed.
