### ISSUE TITLE
Retire Marquand Vault Feature

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/pul_library_drupal#1722]
At https://library.princeton.edu/marquand/vault

1. The data in this feature (content from voyger codes rcppz and sax) hasn't been updated in some years. The UI in drupal has less than 8,000 items and the catalog links to over 12,000. 
2. The catalog provides a view that can used to group the same data https://catalog.princeton.edu/catalog?utf8=%E2%9C%93&f1=all_fields&q1=&op2=AND&f2=author&q2=&op3=AND&f3=title&q3=&f_inclusive%5Badvanced_location_s%5D%5B%5D=rcppz&f_inclusive%5Badvanced_location_s%5D%5B%5D=sax&range%5Bpub_date_start_sort%5D%5Bbegin%5D=&range%5Bpub_date_start_sort%5D%5Bend%5D=&sort=score+desc%2C+pub_date_start_sort+desc%2C+title_sort+asc&search_field=advanced&commit=Search. 
3. The bib IDs will also all change when Alma comes up. 

We could route the vault link to a landing page in the marquand site that could take you into the catalog view for those two locations.

**Comment by axamei** [comment]
Received confirmation from stakeholders that we can retire this feature.

Updated link in left sidebar to take patrons to the catalog view for the two locations. 

@kevinreiss  Do we want to setup a redirect for /marquand/vault to go to that same catalog view?

**Comment by axamei** [comment]
To do:

- [ ] Purge "Marquand Rare Book" content type
- [ ] Purge panel page related to the Marquand Rare Books Vault List
- [ ] Purge marquand_rare_books_vault feature
