### ISSUE TITLE
Remove unused content types

### ISSUE THREAD

**Issue by axamei** [pulibrary/pul_library_drupal#1741]
Remove content types with no content:

- [ ] Article
- [ ] Library Privilege Group
- [ ] Person
- [x] Voyager Locations

**Comment by kevinreiss** [comment]
Can we include this one in the retire list?

https://library.princeton.edu/collections/highlights

Seems like it's been subsumed by news.

**Comment by kevinreiss** [comment]
Site will be archived and shutdown this upcoming summer. No need to do this to support an automated migration at this point. Closing.
