### ISSUE TITLE
Remove "CAMS" Subsite Content

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/pul_library_drupal#1778]
[ ] Delete all content under https://library.princeton.edu/cams
[ ] Remove associated features

**Comment by christinach** [comment]
they moved to confluence https://lib-confluence.princeton.edu/display/ResourceDescription/Resource+Description

**Comment by kevinreiss** [comment]
@carolyncole actually built a drupal bulk task to do this but we've never run it in production.

**Comment by kevinreiss** [comment]
fionally did this. All CAMS pages are deleted.
