### ISSUE TITLE
libweb urls should not be on the server

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/pul_library_drupal#1794]
[libweb_urls_uniq.txt](https://github.com/pulibrary/pul_library_drupal/files/7339665/libweb_urls_uniq.txt)
line 2 & 3 

simmilar to https://github.com/pulibrary/special_collections/issues/679

These should all be removed...

**Comment by kevinreiss** [comment]
Think we've gotten these. I suppose we should probably traverse the database dump for the sake of completeness.
