### ISSUE TITLE
DPUL Bento Search Is Broken

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/pul_library_drupal#1818]
Seems to be a global issue. 

Example: https://library.princeton.edu/find/all/thomas%20jefferson%27s%20haitian%20politics%3A%20myths%20
https://library.princeton.edu/utils/dpulsearch/any?query=thomas%20jefferson%27s%20haitian%20politics%3A%20myths%20&sid=library-main

~~The issue is possibly that the bento box doesn't handle the case when a dpulsearch has zero results. ~~

Actually a global problem. Dpul was migrated and the JSON structure of the response changed to match that of Orangelight.

**Comment by kevinreiss** [comment]
Need to fix via this issue

https://github.com/pulibrary/discoveryutils/pull/201

**Comment by carolyncole** [comment]
There is an issue in dpul to allow for more metadata to come through https://github.com/pulibrary/dpul/issues/1277

**Comment by kevinreiss** [comment]
This has been addressed.
