### ISSUE TITLE
Refrain from using title attributes unless an element needs a tooltip to explain it.

### ISSUE THREAD

**Issue by christinach** [pulibrary/pul_library_drupal#1838]
The "title" attributes on the top-level menu items are redundant, and appear over the flyout, making it difficult to navigate at times
![Screen Shot 2022-01-05 at 12 43 44 PM](https://user-images.githubusercontent.com/9905193/148263940-2023397e-bf7a-479d-aeb2-66d66f99dcde.png)
.

**Comment by kevinreiss** [comment]
I *think* these can be purged in Drupal's admin page for editing the contents of the menu.

**Comment by christinach** [comment]
We made the changes in production.
