### ISSUE TITLE
Upgrade node 

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/pul_library_drupal#1910]
Currently, we are on node 11, which has been EOL for some time.  We cannot upgrade node without also upgrading (or replacing) gulp.

**Comment by maxkadel** [comment]
Context: Per @carolyncole this is only used during deployment, not in the application itself (how we compile the theme).

**Comment by christinach** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DACS-Maintenance-5da0db919c4ddf0001b2eb92/issues/pulibrary/pul_library_drupal/1910?planning-poker) with Zenhub @kevinreiss @maxkadel @regineheberlein @rladdusaw @sandbergja
