### ISSUE TITLE
Trying to update the library blogs block fails with a server error

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/pul_library_drupal#1914]
**Expected behavior**
Users can use the "list links" menu item to edit this block

**Actual behavior**
Error message: "The website encountered an unexpected error. Please try again later."

**Steps to replicate**

1. Go to https://library.princeton.edu/user and log in
1. Go to https://library.princeton.edu/news
2. On the right-hand side of this page there is a block called Library Blogs
3. click the block's cog
4. Choose List links

**Impact of this bug**
This leaves users unable to edit the links block.  It is not a rush for now.

**Datadog error**
https://app.datadoghq.com/logs?query=menu-library-news-and-events&cols=host%2Cservice&event=AQAAAYJp5RDg4EjDyQAAAABBWUpwNVJZLUFBQmRCNlNVN1M3R093QU4&index=&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1659630459102&to_ts=1659634059102&live=true

**Comment by VickieKarasic** [comment]
Hi @sandbergja, I wanted to check on this issue and see if/when we may be able to look more in depth at the error. I received a message from the user that it's still not a rush for now, but they would like to be able to update it eventually. Thanks!

**Comment by sandbergja** [comment]
One of the links in this menu has invalid attributes.  Just resetting all the invalid attributes back to default gets things working again locally:
```
 UPDATE menu_links SET options='a:1:{s:10:"attributes";a:0:{}}' WHERE mlid=2010;
```

**Comment by sandbergja** [comment]
We did the following:

1. Ran the query on staging
2. Confirmed that it's possible to list these links on staging
3. Backed up the prod database.
4. Ran the query on prod
5. Confirmed that it's possible to list these links on prod.

@VickieKarasic could you please confirm that it's acting as expected?

**Comment by sandbergja** [comment]
The stakeholder confirmed that this issue is resolved.  Closing!
