### ISSUE TITLE
Address critical dependabots

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/pul_library_drupal#1915]
- [x] https://github.com/pulibrary/pul_library_drupal/security/dependabot/40
- [x] https://github.com/pulibrary/pul_library_drupal/security/dependabot/35
- [x] https://github.com/pulibrary/pul_library_drupal/security/dependabot/34

**Comment by maxkadel** [comment]
It appears that the last remaining dependency on dependabot/64 is `gulp-sass-lint`, which is no longer being maintained. There is no one-to-one replacement that does not have the same vulnerable dependency, and simply removing the linter from the package.json and the gulpfile appears to break deployment in a way I don't currently understand.
