### ISSUE TITLE
Migrate Mendel Valva Sheet Music Content Type List

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/pul_library_drupal#1984]
This content is still a useful access point. Decide where to move it. Mendel staff said the ability to filter by composer and date is particular approach. 

Original data is here: https://docs.google.com/spreadsheets/d/1DVIZZLwUyUr_sdchHtNCyb5wdiQJaYdb-Qsc9BImV7g/edit#gid=1363578195

Requirements:

1. This static content, new entries are not being created
2. The goal is for the items to be available in the catalog when they are digitized. Mendel is staff is digizting a few dozen per month. There are several thousand left to go. Catalog are all created for those, and a record is unsuppressed when the digitization is completed, added to figgy, and linked to the record. 
3. While digitization is in progress Mendel would like the list of records to available at a stable URL where users have the ability to search by Composer, Arranger, Lyricist, Publisher, general keyword and filter by year. 

Follow-up Questions for Mendel Staff

1. Would it possible to just unsuppress the records and allow users to explore the metadata as a set in the catalog? This is the ultimate end state, there will not be a "special" search interface like the current Drupal site when digitization is complete. 
2. If this is acceptable, could reference the new "set" in the catalog from the parent collection record?

**Comment by kevinreiss** [comment]
Mendel staff like this idea. They asked two things be added

1. Add a 710 note to All Valva records so the collection can be easily pulled together as a set in the catalog
2. Add note to all non-digitized records indicating that they can be digitized upon request. 
Example record: https://catalog.princeton.edu/catalog/99118377683506421

**Comment by kevinreiss** [comment]
Talk to Mark Z. about a plan to do these bulk updates in Alma.

**Comment by mzelesky** [comment]
It might be better to use an 830 field with a $5 NjP.

As for a note that they can be digitized on request, it could be put in a 500 field.

Is there a document that lists all the Valva entries?

**Comment by kevinreiss** [comment]
The spreadsheet in the first comment is the source data for the records. I don't actually know offhand on how to pull them all together as a set in Alma.

**Comment by kevinreiss** [comment]
Work mendel staff for an update 5/31.

**Comment by kevinreiss** [comment]
We meet with Mendel staff on Monday about this.

**Comment by kevinreiss** [comment]
To Do Items

- [ ] 1. Instead of 2 710 Fields for the collection title, we have one preferred 830 Field, and a second 490 field? What happens in catalog indexing for these items?
- [ ] 4. Add a 500 note stating that items in the collection can be digitized on dema

nd.

**Comment by kevinreiss** [comment]
Future questions:

1. No titles problem: https://catalog.princeton.edu/catalog/99118377683506421. Can fix this by making constituent records related to the collection (i.e. host) record. 
2. How to link the collection record with member records: https://catalog.princeton.edu/catalog/9924347793506421?

**Comment by kevinreiss** [comment]
@mzelesky should we create a Alma Config ticket for the "short-term" option we discussed yesterday?

**Comment by kevinreiss** [comment]
Blocked by https://github.com/PrincetonUniversityLibrary/alma-config/issues/548. Once this is done these items can be deleted from the Drupal site.

**Comment by kevinreiss** [comment]
Fleshed out the details of this updates to the catalog with @mzelesky and Brittany from Mendel today 4/18/2024.

**Comment by kevinreiss** [comment]
With the work of the alma team complete in terms of making these records visible we can close this issue.
