### ISSUE TITLE
Move to new mail relay server

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/pul_library_drupal#2056]
Review https://github.com/pulibrary/pul_library_drupal/pull/2046.  Confirm that the following is true after deploying to prod:

- I can still send and receive emails
- /var/log/mail on lib-ponyexpr-prod shows that the mails are sent successfully
- For a rails app, make sure that `enable_starttls` is false.  See https://github.com/pulibrary/orangelight/pull/4026 and https://github.com/pulibrary/pdc_describe/pull/1843 for examples.
- For drupal only: The SMTP server needs to be updated manually here: https://library.princeton.edu/admin/config/system/smtp and the equivalent staging URL.

 Please put your name next to each checkbox you decide to work on.

**Comment by maxkadel** [comment]
Can send email!
