### ISSUE TITLE
Migrate Labor Union Page to Libguides

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/pul_library_drupal#2067]
The URL https://library.princeton.edu/econlib/laborunion needs to be migrated to a libguide under the Industrial and Labor Relations guide section. Bobray is going to work Charissa in IR on this during the month of July.

**Comment by kevinreiss** [comment]
Asked Bobray for update 7.24.

**Comment by sandbergja** [comment]
This will go into static tables instead, the table is too big for libguides.  @kevinreiss will make a new ticket

**Comment by kevinreiss** [comment]
Close in favor of https://github.com/pulibrary/static-tables/issues/188.
