### ISSUE TITLE
create a banner with an end date for migrated sites

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/pul_library_drupal#2072]
We recently created https://library-migrated.lib.princeton.edu and fpul-migrated.lib.princeton.edu

Could we please create a banner announcing a day when these VMs and domain will actually be shut down. It is my hope that they will not be supported in perpetuity.

**Comment by kevinreiss** [comment]
We can post an alert on the sites Francis. The plan is to keep them up for the rest of the year. However I plan to check back in a few weeks to see if we can do it sooner.

**Comment by kevinreiss** [comment]
Banners are updated. Had to update base_url values in princeton to ensure special collections displayed properly on library-migrated.
